include:
  - project: hpc/gitlab-upload-logs
    file: enable-upload.yml
  - project: hpc/gitlab-pipelines
    file: github-project-pipelines.gitlab-ci.yml

variables:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 3

spacktainerize:
  needs: []
  trigger:
    include:
      - project: hpc/spacktainerizer
        file: /build-spack-container.yml
        ref: compiler-mods
    strategy: depend
  variables:
    PACKAGE_NAME: neuron
    SPACK_CUSTOMIZATION: |
      apt-get install wget
      wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
      echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
      apt-get install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
      source /opt/intel/oneapi/setvars.sh
      spack compiler find
      spack add neuron+coreneuron
      spack add libsonata-report@1.1.1
      spack config add "packages:neuron:require:'%intel'"
      spack config add "packages:coreneuron:require:'%intel'"