include:
  - project: hpc/gitlab-pipelines
    file:
      - spack-build-components.gitlab-ci.yml
      - github-project-pipelines.gitlab-ci.yml
    ref: '$GITLAB_PIPELINES_BRANCH'
  - project: hpc/gitlab-upload-logs
    file: enable-upload.yml

variables:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 3

spacktainerize:
  needs: []
  trigger:
    include:
      - project: hpc/spacktainerizer
        file: /build-spack-container.yml
        ref: compiler-mods
    strategy: depend
  variables:
    PACKAGE_NAME: neuron
    SPACK_CUSTOMIZATION: |
      curl https://registrationcenter-download.intel.com/akdlm/irc_nas/19030/l_dpcpp-cpp-compiler_p_2022.2.1.16991.sh --output l_dpcpp-cpp-compiler_p_2022.2.1.16991.sh
      sh ./l_dpcpp-cpp-compiler_p_2022.2.1.16991.sh -a --silent --eula accept --install-dir /opt/software/intel/oneapi
      source /opt/software/intel/oneapi/setvars.sh
      spack compiler find
      spack add neuron+coreneuron
      spack add libsonata-report@1.1.1
      spack config add "packages:neuron:require:'%intel'"
      spack config add "packages:coreneuron:require:'%intel'"
