include:
  - project: hpc/gitlab-upload-logs
    file: enable-upload.yml
  - project: hpc/gitlab-pipelines
    file: github-project-pipelines.gitlab-ci.yml

variables:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 3

spacktainerize:
  needs: []
  trigger:
    include:
      - project: hpc/spacktainerizer
        file: /build-spack-container.yml
        ref: compiler-mods
    strategy: depend
  variables:
    PACKAGE_NAME: neuron
    SPACK_CUSTOMIZATION: |
      apt-get install wget
      wget https://registrationcenter-download.intel.com/akdlm/irc_nas/19030/l_dpcpp-cpp-compiler_p_2022.2.1.16991.sh
      sh ./l_dpcpp-cpp-compiler_p_2022.2.1.16991.sh -a --silent --eula accept
      source ~/intel/oneapi/setvars.sh
      spack compiler find
      spack add neuron+coreneuron
      spack add libsonata-report@1.1.1
      spack config add "packages:neuron:require:'%intel'"
      spack config add "packages:coreneuron:require:'%intel'"