include:
  - project: hpc/gitlab-upload-logs
    file: enable-upload.yml
  - project: hpc/gitlab-pipelines
    file: github-project-pipelines.gitlab-ci.yml

variables:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 3

spacktainerize:
  needs: []
  trigger:
    include:
      - project: hpc/spacktainerizer
        file: /build-spack-container.yml
        ref: compiler-mods
    strategy: depend
  variables:
    PACKAGE_NAME: neuron
    SPACK_CUSTOMIZATION: |
      spack install intel-oneapi-compilers
      spack load intel-oneapi-compilers
      spack compiler find
      spack add neuron+coreneuron
      spack add libsonata-report@1.1.1
      spack config add "packages:neuron:require:'%oneapi'"
      spack config add "packages:coreneuron:require:'%oneapi'"