[project]
name = "NEURON"
description = "Empirically-based simulator for modeling neurons and networks of neurons"
authors = [{name="Michael Hines", email="michael.hines@yale.edu"},
{name="Yale"},
{name="Blue Brain Project"}]
# maintainer is the field chosen for docs `contributors`
maintainers = [{name="Michael Hines"}]
license = {file ="Copyright"}
readme = {file = "README.md", content-type="text/markdown"}
classifiers = [
   "Programming Language :: C++",
   "Programming Language :: Python",
   "Topic :: Scientific/Engineering",
   "License :: Other/Proprietary License",
]
version="0.1"
requires-python = ">=3.8"
dependencies = ["numpy>=1.9.3", "packaging", "find_libpython", "setuptools"]

[project.urls]
website="https://neuron.yale.edu/neuron/"
Source = "https://github.com/neuronsimulator/nrn"

[build-system]
requires = [
"setuptools-scm",
"scikit-build-core",
"cython<3",
# taken from the CI script (3.9 is for MacOS on ARM)
"numpy",
    "Jinja2>=2.9.3",
    "PyYAML>=3.13",
#"numpy==1.17.5;python_version==3.8.*,numpy==1.21.3;python_version==3.9.*,numpy==1.21.3;python_version==3.10.*,numpy==1.23.5;python_version==3.11.*,numpy==1.26.0;python_version==3.12.*",
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
# let CMake decide what to put in the wheel
wheel.packages = []

[tool.scikit-build.cmake.define]
MACOSX_DEPLOYMENT_TARGET="11.0"
NRN_BINARY_DIST_BUILD="ON"
NRN_WHEEL_STATIC_READLINE="ON"
LINK_AGAINST_PYTHON="OFF"
# coreNEURON is enabled for shipped wheels
NRN_ENABLE_CORENEURON="ON"
# RX3D is always enabled, but since it's built using `cythonize`, we disable it for now
NRN_ENABLE_RX3D="OFF"
# interviews is always enabled
NRN_ENABLE_INTERVIEWS="ON"
IV_ENABLE_X11_DYNAMIC="ON"
# specific options
NRN_ENABLE_PYTHON_DYNAMIC="ON"
NRN_ENABLE_MODULE_INSTALL="OFF"
NRN_ENABLE_REL_RPATH="ON"
CMAKE_VERBOSE_MAKEFILE="OFF"
# for coreNEURON
CORENRN_ENABLE_OPENMP="ON"
NMODL_ENABLE_PYTHON_BINDINGS="ON"
# as a workaround for the fact that MPI headers are platform-specific
# NOTE: these MUST be set in the CI env!
NRN_MPI_DYNAMIC = {env="NRN_MPI_DYNAMIC"}
CMAKE_PREFIX_PATH = {env="CMAKE_PREFIX_PATH"}

[tool.setuptools_scm]

[tool.cibuildwheel]
manylinux-aarch64-image = "docker.io/neuronsimulator/neuron_wheel:latest-gcc9-aarch64"

[tool.cibuildwheel.macos]
environment = { CMAKE_PREFIX_PATH="/opt/nrnwheel/ncurses;/opt/nrnwheel/readline;/usr/x11" }
[tool.cibuildwheel.linux]
# we set NRN_MPI_DYNAMIC here since we have full control of the container
environment = { CMAKE_PREFIX_PATH="/nrnwheel/ncurses;/nrnwheel/readline", NRN_MPI_DYNAMIC="/nrnwheel/openmpi/include;/nrnwheel/mpich;/include/nrnwheel/mpt/include" }
repair-wheel-command = "auditwheel -v repair -w {dest_dir} {wheel} --exclude 'libgomp.so.1' --exclude 'libnrniv.so'"
